analytics: {}
color:
  brandColors:
    - '#915E0F'
    - '#393C43'
    - '#D73948'
    - '#CDE0DE'
    - '#F1CD39'
  brandStrength: 0.5
  lightness: 0
  rhythmicContrast: 0.5
  saturation: 0.75
cta: {}
layout_spectrum: 0.59426
name: Crusten
opengraph: {}
purpose: []
typography_spectrum: 0.06543
