name: Crusten
favicon: null
layout_spectrum: 0.59426
typography_spectrum: 0.06431
title: Crusten
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#271418'
    - '#d0dcd2'
    - '#d9532f'
    - '#378085'
    - '#9b9294'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
