name: crust
favicon: null
layout_spectrum: 0.9463088731281459
typography_spectrum: 0.06431
title: Crusten
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6470157268922776
  lightness: 0.49027768592350185
  saturation: 0.6540097985416651
  rhythmicContrast: 0.880333243869245
purpose: []
