typography_spectrum: 0.06543
color:
  brandColors:
    - '#915E0F'
    - '#393C43'
    - '#D73948'
    - '#CDE0DE'
    - '#F1CD39'
  brandStrength: 0.5
  lightness: 0
  rhythmicContrast: 0.5
  saturation: 0.75
opengraph: {}
layout_spectrum: 0.59426
analytics: {}
name: Crusten
cta: {}
title: CRUSTEN
purpose: []
